"""
ViGiL — Agent 15: ATT&CK Navigator Export Agent
Generates ATT&CK Navigator layer JSON for import into https://mitre-attack.github.io/attack-navigator/
"""
from __future__ import annotations

import json
from pathlib import Path
from loguru import logger

from models import ATTACKNavigatorResult


# ATT&CK Navigator color scale (confidence → color)
def _confidence_to_color(confidence: float) -> str:
    if confidence >= 0.8:
        return "#ff0000"  # High confidence — red
    elif confidence >= 0.6:
        return "#ff8c00"  # Medium-high — orange
    elif confidence >= 0.4:
        return "#ffd700"  # Medium — yellow
    else:
        return "#90ee90"  # Low — light green


def run_attack_navigator_export(
    techniques: list[dict],
    sample_name: str = "sample",
    output_dir: Path = None,
) -> ATTACKNavigatorResult:
    logger.info("[ATTACKNavigator] Generating ATT&CK Navigator layer")

    # Build technique entries
    technique_entries = []
    for tech in techniques:
        technique_id = tech.get("technique_id", "")
        confidence = tech.get("confidence", 0.5)

        if not technique_id:
            continue

        technique_entries.append({
            "techniqueID": technique_id,
            "tactic": tech.get("tactic", "").lower().replace(" ", "-"),
            "color": _confidence_to_color(confidence),
            "comment": f"ViGiL detected: {tech.get('technique_name', '')} (confidence: {confidence:.0%})",
            "enabled": True,
            "metadata": [],
            "links": [],
            "showSubtechniques": False,
            "score": int(confidence * 100),
        })

    layer = {
        "name": f"ViGiL Analysis — {sample_name}",
        "versions": {
            "attack": "15",
            "navigator": "4.9.1",
            "layer": "4.5",
        },
        "domain": "enterprise-attack",
        "description": f"ATT&CK layer generated by ViGiL for sample: {sample_name}",
        "filters": {
            "platforms": ["Windows"],
        },
        "sorting": 3,
        "layout": {
            "layout": "side",
            "aggregateFunction": "average",
            "showID": True,
            "showName": True,
            "showAggregateScores": True,
            "countUnscored": False,
        },
        "hideDisabled": False,
        "techniques": technique_entries,
        "gradient": {
            "colors": ["#90ee90", "#ffd700", "#ff8c00", "#ff0000"],
            "minValue": 0,
            "maxValue": 100,
        },
        "legendItems": [
            {"label": "Low Confidence", "color": "#90ee90"},
            {"label": "Medium Confidence", "color": "#ffd700"},
            {"label": "High Confidence", "color": "#ff0000"},
        ],
        "metadata": [
            {"name": "generated_by", "value": "ViGiL v1.0.0"},
            {"name": "sample", "value": sample_name},
        ],
        "links": [],
        "showTacticRowBackground": True,
        "tacticRowBackground": "#0d1117",
        "selectTechniquesAcrossTactics": True,
        "selectSubtechniquesWithParent": False,
    }

    # Save to file
    nav_path = None
    if output_dir:
        nav_path = output_dir / "attack_layer.json"
        with open(nav_path, "w") as f:
            json.dump(layer, f, indent=2)
        logger.info(f"[ATTACKNavigator] Saved layer to: {nav_path}")

    return ATTACKNavigatorResult(
        layer_json=layer,
        navigator_json_path=str(nav_path) if nav_path else None,
    )
