"""
ViGiL — Agent 16: STIX/TAXII Export Agent
Generates STIX 2.1 bundles for OpenCTI, MISP, and TAXII server import.
"""
from __future__ import annotations

import json
import uuid
from datetime import datetime, timezone
from pathlib import Path
from loguru import logger

from models import STIXResult


def _stix_id(type_: str) -> str:
    return f"{type_}--{uuid.uuid4()}"


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def run_stix_export(
    sha256: str,
    filename: str,
    family: str | None,
    capabilities: list[str],
    techniques: list[dict],
    ips: list[str],
    domains: list[str],
    urls: list[str],
    threat_level: str,
    output_dir: Path = None,
) -> STIXResult:
    logger.info("[STIX] Generating STIX 2.1 bundle")

    objects = []
    now = _now()

    # ── Identity (tool producer) ─────────────────────────────────────────────
    identity_id = _stix_id("identity")
    identity = {
        "type": "identity",
        "spec_version": "2.1",
        "id": identity_id,
        "created": now,
        "modified": now,
        "name": "ViGiL Malware Analysis Platform",
        "identity_class": "system",
        "description": "Automated malware analysis report generated by ViGiL v1.0.0",
    }
    objects.append(identity)

    # ── Malware object ───────────────────────────────────────────────────────
    malware_id = _stix_id("malware")
    malware_labels = []
    if "ransomware" in str(capabilities).lower():
        malware_labels.append("ransomware")
    if "credential" in str(capabilities).lower() or "keylog" in str(capabilities).lower():
        malware_labels.append("infostealer")
    if "inject" in str(capabilities).lower():
        malware_labels.append("trojan")
    if not malware_labels:
        malware_labels.append("trojan")

    malware_obj = {
        "type": "malware",
        "spec_version": "2.1",
        "id": malware_id,
        "created": now,
        "modified": now,
        "created_by_ref": identity_id,
        "name": family or "Unknown Malware",
        "malware_types": malware_labels,
        "is_family": bool(family and family.lower() not in ("unknown", "novel / unknown family")),
        "capabilities": capabilities[:10],
        "description": f"Malware sample analyzed by ViGiL. Threat level: {threat_level}. SHA256: {sha256}",
    }
    objects.append(malware_obj)

    # ── File Indicator ───────────────────────────────────────────────────────
    indicator_id = _stix_id("indicator")
    indicator = {
        "type": "indicator",
        "spec_version": "2.1",
        "id": indicator_id,
        "created": now,
        "modified": now,
        "created_by_ref": identity_id,
        "name": f"SHA256 — {filename}",
        "pattern": f"[file:hashes.'SHA-256' = '{sha256}']",
        "pattern_type": "stix",
        "valid_from": now,
        "labels": ["malicious-activity"],
        "description": f"Malicious file indicator for sample: {filename}",
        "indicator_types": ["malicious-activity"],
    }
    objects.append(indicator)

    # ── Relationship: indicator → malware ────────────────────────────────────
    rel_indicator_malware = {
        "type": "relationship",
        "spec_version": "2.1",
        "id": _stix_id("relationship"),
        "created": now,
        "modified": now,
        "created_by_ref": identity_id,
        "relationship_type": "indicates",
        "source_ref": indicator_id,
        "target_ref": malware_id,
    }
    objects.append(rel_indicator_malware)

    # ── Network Indicators ───────────────────────────────────────────────────
    for ip in ips[:10]:
        ip_id = _stix_id("indicator")
        objects.append({
            "type": "indicator",
            "spec_version": "2.1",
            "id": ip_id,
            "created": now,
            "modified": now,
            "name": f"C2 IP: {ip}",
            "pattern": f"[network-traffic:dst_ref.type = 'ipv4-addr' AND network-traffic:dst_ref.value = '{ip}']",
            "pattern_type": "stix",
            "valid_from": now,
            "indicator_types": ["malicious-activity"],
            "labels": ["c2"],
        })

    for domain in domains[:10]:
        dom_id = _stix_id("indicator")
        objects.append({
            "type": "indicator",
            "spec_version": "2.1",
            "id": dom_id,
            "created": now,
            "modified": now,
            "name": f"C2 Domain: {domain}",
            "pattern": f"[domain-name:value = '{domain}']",
            "pattern_type": "stix",
            "valid_from": now,
            "indicator_types": ["malicious-activity"],
            "labels": ["c2"],
        })

    # ── Attack Patterns (from MITRE) ─────────────────────────────────────────
    for tech in techniques[:8]:
        ap_id = _stix_id("attack-pattern")
        objects.append({
            "type": "attack-pattern",
            "spec_version": "2.1",
            "id": ap_id,
            "created": now,
            "modified": now,
            "created_by_ref": identity_id,
            "name": tech.get("technique_name", "Unknown"),
            "description": tech.get("description", ""),
            "external_references": [
                {
                    "source_name": "mitre-attack",
                    "external_id": tech.get("technique_id", ""),
                    "url": f"https://attack.mitre.org/techniques/{tech.get('technique_id', '')}",
                }
            ],
        })

    # ── Report ───────────────────────────────────────────────────────────────
    report_id = _stix_id("report")
    report = {
        "type": "report",
        "spec_version": "2.1",
        "id": report_id,
        "created": now,
        "modified": now,
        "created_by_ref": identity_id,
        "name": f"ViGiL Malware Analysis Report — {filename}",
        "description": f"Automated analysis of {filename} (SHA256: {sha256}). Threat level: {threat_level}.",
        "report_types": ["malware"],
        "published": now,
        "object_refs": [obj["id"] for obj in objects],
    }
    objects.append(report)

    # ── Bundle ───────────────────────────────────────────────────────────────
    bundle = {
        "type": "bundle",
        "id": _stix_id("bundle"),
        "objects": objects,
    }

    # Save to file
    stix_path = None
    if output_dir:
        stix_path = output_dir / "report.stix.json"
        with open(stix_path, "w") as f:
            json.dump(bundle, f, indent=2)
        logger.info(f"[STIX] Saved STIX bundle to: {stix_path}")

    return STIXResult(
        stix_bundle=bundle,
        stix_json_path=str(stix_path) if stix_path else None,
        objects_generated=len(objects),
    )
